import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { env } from './config/env.js';
import { authenticate } from './middleware/auth.js';
import { errorHandler, notFound } from './middleware/errors.js';
import { authRouter } from './modules/auth/router.js';
import { roomsRouter } from './modules/rooms/router.js';
import { guestsRouter } from './modules/guests/router.js';
import { documentsRouter } from './modules/guests/documents-router.js';
import { reservationsRouter } from './modules/reservations/router.js';
import { staysRouter } from './modules/stays/router.js';
import { billingRouter } from './modules/billing/router.js';
import { housekeepingRouter } from './modules/housekeeping/router.js';
import { reportsRouter } from './modules/reports/router.js';
import { usersRouter } from './modules/users/router.js';

export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: env.WEB_ORIGIN.split(',').map(x => x.trim()), credentials: false }));
app.use(express.json({ limit: '1mb' }));
app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.use('/api/auth', authRouter);
app.use('/api', authenticate);
app.use('/api/rooms', roomsRouter);
app.use('/api/guests', documentsRouter);
app.use('/api/guests', guestsRouter);
app.use('/api/reservations', reservationsRouter);
app.use('/api/stays', staysRouter);
app.use('/api/billing', billingRouter);
app.use('/api/housekeeping', housekeepingRouter);
app.use('/api/reports', reportsRouter);
app.use('/api/users', usersRouter);
app.use(notFound);
app.use(errorHandler);
